### ISSUE TITLE
Update ArtNet output configuration + FadeCandy Server for OPC Channel 1 for Broader support

### ISSUE THREAD

**Issue by snowake4me** [balenalabs-incubator/led-pixel-controller#14]
Per another forum thread, was curious to use xLights to interface to FadeCandy Server running on the Raspberry Pi.  Made the changes discussed in that thread (updating the FadeCandy server.json file) to listen on OPC Channel 1, since xLights can't be configured for channel 0.

Alas - that broke the existing Glediator -> ArtNet (-> FadeCandy) functionality of this project.  Suspect it's a quick / trivial adjustment to the ArtNet server config to make a corresponding change to it's OPC output configuration.

Is there any downside to shifting the whole project from OPC Channel 0 to Channel 1 for broader interoperability?  Had hoped to contribute by submitting a PR with both these changes -- but I'm struggling to find the authoritative documentation for the ArtNet server.  My hack-y attempts to edit:

artnet/src/artnet-server_fc.py

Have not yet yielded positive results.  Will update the issue, or even submit a PR, as I learn more.

Cheers!

**Comment by snowake4me** [comment]
@chrisys I think I've got a working feature branch with this config change working as desired (moving both the fadecandy input and artnet output from OPC channel 0 to channel 1.

**Comment by chrisys** [comment]
Closed in #16 thanks Billy!
