### ISSUE TITLE
Pi 4

### ISSUE THREAD

**Issue by plucker** [balenalabs-incubator/led-pixel-controller#5]
Does this run on a Pi 4? I can't seem to get it to work.  FCSERVER seems to be crashing and if I go to the IP address of the Pi, I get the Glediator interface, not the FCSERVER one.

The Pi is continuously issuing this error:

02.12.20 20:40:39 (+0000)  fcserver  /usr/bin/entry.sh: line 59: /usr/src/app/fcserver-rpi: No such file or directory

And FCSERVER keep trying to restart and hitting the same problem

UPDATE:  I tried on a Pi 3+ and have the same issue.

The instructions here: https://www.balena.io/blog/build-festive-lighting-for-the-holidays-with-balena/

don't show a VNC process running and say that if you connect to the ip of the pi you should get the fadecandy web interface.

**Comment by chrisys** [comment]
Thanks for highlighting, it's definitely not been tested on a Pi 4 but it is currently working on the Pi 3 - I wonder if you used a 64-bit Pi 3 OS? That might cause the issue, but this is something I can look into.

The blog post you linked is the old version (note there's a link at the very top of the post saying it's been updated) - if you check that one out it may make a bit more sense. I made the note a bit bigger to hopefully make it stand out a bit more.

**Comment by plucker** [comment]
Thank you - I missed that note, and will try again with 64-bit OS on a Pi3 to see if that helps

**Comment by chrisys** [comment]
Ah I was thinking that if you had used the 64-bit OS that might be a problem, I've only tested it on the 32-bit one so far - sorry for lack of clarity there. I wonder if there's anything in the build logs that indicate a problem as well (you can find these under releases in the dashboard). That file that's missing is downloaded on demand here: https://github.com/balenalabs-incubator/fadecandy-led-controller/blob/master/fcserver/Dockerfile.template#L6 but if that failed I'd expect the whole build to fail. Nevertheless I will try to grab some time to look at this as well.

**Comment by chrisys** [comment]
@plucker if you download the latest changes and push again Pi 4 should now work, just tested with mine here :)

**Comment by plucker** [comment]
Oh magic, I'll give it a go, been a bit busy this week but probably get to it at the weekend
